### ISSUE TITLE
How to keep previous wizard data when we go back

### ISSUE THREAD

**Issue by tatvasavan** [michaelscodingspot/WPF_MVVMC#14]
Hi Michael,

First, thank you for creating this navigation library. 

I am creating a wizard pattern using this library, and I am facing the issue to keep previous wizard data when we navigate back. I think it is a similar issue that was [reported earlier](https://github.com/michaelscodingspot/WPF_MVVMC/issues/9). I have checked the suggested way but I think still I am missing something and the Back behavior is not working for me.

Could you please explain, where I need to make the changes to this [sample](https://github.com/michaelscodingspot/WPF_MVVMC) to keep and bind the data to the previous wizard?

**Comment by michaelscodingspot** [comment]
Hi @savan-bagtharia ,

Can you be a bit more specific? What data exactly are you trying to keep?

**Comment by tatvasavan** [comment]
Hi Michael,

On the [sample application](https://github.com/michaelscodingspot/WPF_MVVMC), we can add an employee and for that employee, we can add/set value for the Firstname, LastName, Salary on different wizards, and goto next. Now if we go back to the previous wizard, then all values will not be populated there. 

Let's say I have set some values like FirstName = ABC, LastName = XYZ, and Salary = 1000 and after moving to confirm screen, if we go back to other wizards (FirstName, LastName, Salary) then it should display all values.

Based on the documentation, I have changed the value for **HistoricalNavigationMode** but nothing worked.

Let me know if you need any further details.

**Comment by michaelscodingspot** [comment]
Ok, I think I understand the problem.

Changing **HistoricalNavigationMode**  to **UseSavedParameter** won't help because that parameter doesn't do anything in populating the fields in the pages.

I think the best solution for this is a new history mode called "SaveViewModel". It will save a stack of all view models as you advance in history, and going back will use the same ViewModel instance from before.
Like with "SaveParamaterInstance" mode, it can lead to memory leaks because you're leaving instances in memory. But I think it's fine for many applications.

Does that sound like a good solution? If so, I can try and implement it.

**Comment by michaelscodingspot** [comment]
@savan-bagtharia I went ahead and implemented "SaveViewModel" history mode. You can pull latest changes and see how it's used in "Add employee" flow. A new NuGet package (2.3.0) will be available within an hour. I'll update the documentation soon. Enjoy!

**Comment by tatvasavan** [comment]
@michaelscodingspot Thank you for adding the new mode as **SaveViewModel**. That is working fine and keeping the data for the previous wizards.

But, I found one behaviour, when we go back to the previous wizard and if we go to the next then data will be lost for the next wizard. 
e.g. Let's say, I have set values for FirstName = ABC, LastName = XYZ, and Salary = 1000. Now, when we go back to the previous wizard then data will be there (_till FirstName_). But after that when we go to the next wizard (_LastName or Salary_) then data is lost.

Can we get some flexibility to choose/decide, whether we want to keep data on Back/Next? I mean it could handle History Navigation completely in both way (start to end/end to start)

**Comment by michaelscodingspot** [comment]
Sure thing.

As for what you're asking, it's a matter of usage. When clicking "Next" button, the current implementation navigates to a new page and not _going forward in history_. You can easily change it to check if "Forward" is possible and then navigate forward if yes or navigate to a new page otherwise.

In the sample application, in `AddEmployeeViewModel.NextCommand` change from
```
INavigationService navigationService = NavigationServiceProvider.GetNavigationServiceInstance();
AddWizardController controller = navigationService.GetController<AddWizard.AddWizardController>();
controller.Next();
RefreshButtons();
```
to
```
INavigationService navigationService = NavigationServiceProvider.GetNavigationServiceInstance();
AddWizardController controller = navigationService.GetController<AddWizard.AddWizardController>();
if (controller.CanGoForward)
{
    controller.GoForward();
}
else
{
    controller.Next();
}
RefreshButtons();
```

**Comment by michaelscodingspot** [comment]
@savan-bagtharia Closing this issue as it seems all concern were resolved.
